import type { ColorTag } from "./types";

// Mock data - Colors with actual color values
export const COLORS: ColorTag[] = [
  { name: "Blue", color: "#3B82F6" },
  { name: "Teal", color: "#14B8A6" },
  { name: "Mint", color: "#6EE7B7" },
  { name: "Green", color: "#22C55E" },
  { name: "Sage", color: "#84CC16" },
  { name: "Yellow", color: "#EAB308" },
  { name: "Beige", color: "#D4A574" },
  { name: "Brown", color: "#92400E" },
  { name: "Orange", color: "#F97316" },
  { name: "Peach", color: "#FB923C" },
  { name: "Red", color: "#EF4444" },
  { name: "Maroon", color: "#991B1B" },
  { name: "Pink", color: "#EC4899" },
  { name: "Purple", color: "#A855F7" },
  { name: "Navy", color: "#1E3A8A" },
  { name: "Black", color: "#000000" },
  { name: "Grey", color: "#6B7280" },
  { name: "White", color: "#FFFFFF" },
];

// Mock data - Collections
export const COLLECTIONS = [
  "Pastel",
  "Vintage",
  "Retro",
  "Neon",
  "Gold",
  "Light",
  "Dark",
  "Warm",
  "Cold",
  "Summer",
  "Fall",
  "Winter",
  "Spring",
  "Happy",
  "Nature",
  "Earth",
  "Night",
  "Space",
  "Rainbow",
  "Gradient",
  "Sunset",
  "Sky",
  "Sea",
  "Kids",
  "Skin",
  "Food",
  "Cream",
  "Coffee",
  "Wedding",
  "Christmas",
  "Halloween",
];
